### ISSUE TITLE
ImportError in version 1.1.0 on SL6

### ISSUE THREAD

**Issue by vbrik** [WIPACrepo/pyglidein#138]
pyglidein_client started failing on gzk-cm (SL6.7) after update to 1.1.0:

```
Traceback (most recent call last):
  File "/usr/bin/pyglidein_client", line 11, in <module>
    load_entry_point('pyglidein==1.1.0', 'console_scripts', 'pyglidein_client')()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2769, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2422, in load
    return self.resolve()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2428, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.6/site-packages/pyglidein/client.py", line 17, in <module>
    import pyglidein.client_metrics as client_metrics
  File "/usr/lib/python2.6/site-packages/pyglidein/client_metrics.py", line 7, in <module>
    from subprocess import check_output, STDOUT
ImportError: cannot import name check_output

**Comment by dsschult** [comment]
`subprocess.check_output()` is from python2.7.  We can either use the older syntax, or just tell you to get a newer python (from cvmfs, possibly?).
